CREATE TABLE thing (
    id SERIAL PRIMARY KEY,
    type SMALLINT NOT NULL DEFAULT 0,
    name TEXT NOT NULL,
    creator INTEGER REFERENCES thing DEFERRABLE INITIALLY DEFERRED,
    created TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    parent INTEGER REFERENCES thing,
    tabledata JSON NOT NULL DEFAULT '{}'::json
);

CREATE TABLE account (
    loginname TEXT NOT NULL PRIMARY KEY,
    passwordhash TEXT NOT NULL,
    character INTEGER NOT NULL REFERENCES thing,
    created TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
