CREATE TABLE thing (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    creator INTEGER NOT NULL REFERENCES thing DEFERRABLE INITIALLY DEFERRED,
    created TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    parent INTEGER REFERENCES thing,
    tabledata JSON NOT NULL DEFAULT '{}'::json
);

CREATE TABLE account (
    loginname TEXT NOT NULL PRIMARY KEY,
    passwordhash TEXT NOT NULL,
    character INTEGER NOT NULL REFERENCES thing,
    created TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE exit (
    command TEXT NOT NULL,
    source INTEGER NOT NULL REFERENCES thing,
    target INTEGER NOT NULL REFERENCES thing
);
